blueprint:
  name: PB Presence-activated Light
  description: Turn on a light when presence is detected.
  source_url: https://github.com/p8mty/blueprints/blob/main/presence-light-pb.yaml
  domain: automation
  input:
    presence_entity:
      name: Presence Sensor
      description: Presence sensor device
      selector:
        entity:
          domain:
          - binary_sensor
          device_class:
          - occupancy
          multiple: false
    light_target:
      name: Light
      description: Light device
      selector:
        target:
          entity:
          - domain:
            - light
    bright_percentage:
      name: Bright Percentage
      description: Brightness level that the light will turn into once is turned on
      default: 100
      selector:
        number:
          min: 0.0
          max: 100.0
          unit_of_measurement: percentage
          mode: slider
          step: 1.0
    color_temp:
      name: Colour Temperature
      description: Colour temperture that the light will turn into once is turned on
      default: 2700
      selector:
        number:
          min: 2300
          max: 3300
          unit_of_measurement: K
          mode: slider
          step: 50
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 0
      selector:
        number:
          min: 0.0
          max: 3600.0
          unit_of_measurement: seconds
          mode: slider
          step: 1.0
    off_transition:
      name: Transition time
      description: Time in seconds of transition turning off
      default: 0
      selector:
        number:
          min: 0.0
          max: 60.0
          unit_of_measurement: seconds
          mode: slider
          step: 1.0
    light_sensor:
      name: Light sensor
      description: Light sensor to read from
      default: []
      selector:
        entity:
          domain:
          - sensor
          device_class:
          - illuminance
          multiple: false
    light_threshold:
      name: Light threshold
      description: Light sensor‘s lower threshold
      default: 200
      selector:
        number:
          min: 0.0
          max: 255.0
          mode: slider
          step: 1.0
    block_action:
      name: Block Action
      selector:
      default: []
      selector:
        entity:
          domain:
          - input_boolean
          multiple: false
mode: restart
max_exceeded: silent
trigger:
  platform: state
  entity_id: !input presence_entity
  from: 'off'
  to: 'on'
condition:
- condition: numeric_state
  entity_id: !input light_sensor
  below: !input light_threshold
- condition: state
  entity_id: !input block_action
  state: "off"
action:
- alias: Turn on the light
  service: light.turn_on
  target: !input light_target
  data:
    brightness_pct: !input bright_percentage
    kelvin: !input color_temp
- alias: Wait until there is no motion from device
  wait_for_trigger:
    platform: state
    entity_id: !input presence_entity
    from: 'on'
    to: 'off'
- alias: Wait the number of seconds that has been set
  delay: !input no_motion_wait
- alias: Turn off the light
  service: light.turn_off
  target: !input light_target
  data:
    transition: !input off_transition
